/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Classes.Administrador;
import Classes.Lib;
import Classes.PetShop;
import Classes.TipoFuncionario;
import Classes.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author vitor
 */
public class TelaCadastroFuncionario extends javax.swing.JFrame {

    private PetShop petshop;

    /**
     * Creates new form TelaCadastroCliente
     */
    public TelaCadastroFuncionario(PetShop petshop) {
        initComponents();
        this.petshop = petshop;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectCargo = new javax.swing.ButtonGroup();
        botaoCadastrar = new javax.swing.JButton();
        labelNome = new javax.swing.JLabel();
        inputNome = new javax.swing.JTextField();
        labelUsuario = new javax.swing.JLabel();
        inputUsuario = new javax.swing.JTextField();
        labelSenha = new javax.swing.JLabel();
        labelSalario = new javax.swing.JLabel();
        inputSalario = new javax.swing.JTextField();
        tituloPagina = new javax.swing.JLabel();
        radioVendedor = new javax.swing.JRadioButton();
        radioVeterinario = new javax.swing.JRadioButton();
        labelCargo = new javax.swing.JLabel();
        inputSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        botaoCadastrar.setText("Cadastrar");
        botaoCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCadastrarMouseClicked(evt);
            }
        });
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        labelNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNome.setText("Nome");

        inputNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNomeActionPerformed(evt);
            }
        });

        labelUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelUsuario.setText("Usuário");

        inputUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUsuarioActionPerformed(evt);
            }
        });

        labelSenha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelSenha.setText("Senha");

        labelSalario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelSalario.setText("Salário");

        inputSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSalarioActionPerformed(evt);
            }
        });

        tituloPagina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tituloPagina.setText("Cadastro de Funcionários");

        selectCargo.add(radioVendedor);
        radioVendedor.setText("Vendedor");

        selectCargo.add(radioVeterinario);
        radioVeterinario.setText("Veterinário");

        labelCargo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelCargo.setText("Cargo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(tituloPagina)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelUsuario)
                            .addComponent(labelNome)
                            .addComponent(labelSenha)
                            .addComponent(labelSalario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputNome)
                            .addComponent(inputUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                            .addComponent(inputSenha)
                            .addComponent(inputSalario)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCargo)
                        .addGap(18, 18, 18)
                        .addComponent(radioVendedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioVeterinario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(tituloPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsuario)
                    .addComponent(inputUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(radioVendedor)
                                .addComponent(radioVeterinario)
                                .addComponent(labelCargo)))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSenha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSalario))
                        .addGap(68, 68, 68))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void inputNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNomeActionPerformed

    private void inputUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUsuarioActionPerformed

    private void inputSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSalarioActionPerformed

    private void botaoCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadastrarMouseClicked
        if (inputNome.getText().isEmpty() || inputSalario.getText().isEmpty() || inputSenha.getPassword().length==0 || inputUsuario.getText().isEmpty() || (!radioVendedor.isSelected() && !radioVeterinario.isSelected())) {
            JOptionPane.showMessageDialog(this, "Preencha todos os dados", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Se o usuário for administrador...
        if (petshop.getSessaoAtual().getCargo() == TipoFuncionario.ADMINISTRADOR) {

            String nome = inputNome.getText();
            String usuario = inputUsuario.getText();
            String senha = String.copyValueOf(inputSenha.getPassword());
            double salario = Double.parseDouble(inputSalario.getText());
            Administrador admin = (Administrador) petshop.getSessaoAtual();
            boolean sucesso = false;
            if (radioVendedor.isSelected()) {
                sucesso = admin.cadastrarVendedor(nome, usuario, senha, salario);
            } else if (radioVeterinario.isSelected()) {
                sucesso = admin.cadastrarVeterinario(nome, usuario, senha, salario);
            }
            if (sucesso) {
                JOptionPane.showMessageDialog(this, "Funcionário cadastrado com sucesso", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Funcionário já cadastrado", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            inputNome.setText("");
            inputUsuario.setText("");
            inputSalario.setText("");
            inputSenha.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Acesso negado", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botaoCadastrarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JTextField inputNome;
    private javax.swing.JTextField inputSalario;
    private javax.swing.JPasswordField inputSenha;
    private javax.swing.JTextField inputUsuario;
    private javax.swing.JLabel labelCargo;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelSalario;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JRadioButton radioVendedor;
    private javax.swing.JRadioButton radioVeterinario;
    private javax.swing.ButtonGroup selectCargo;
    private javax.swing.JLabel tituloPagina;
    // End of variables declaration//GEN-END:variables
}
