/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Classes.Lib;
import Classes.PetShop;
import javax.swing.JOptionPane;

/**
 *
 * @author danilo
 */
public class TelaMenuAdministrador extends javax.swing.JFrame {

    PetShop petshop;
    /**
     * Creates new form TelaMenuAdministrador
     */
    public TelaMenuAdministrador(PetShop petshop) {
        initComponents();
        this.petshop = petshop;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonCadastrarNovoCliente = new javax.swing.JButton();
        jButtonCadastrarNovoVendedor = new javax.swing.JButton();
        jButtonCadastrarNovoVeterinario = new javax.swing.JButton();
        jButtonCadastrarNovoProduto = new javax.swing.JButton();
        jButtonCadastrarNovoServico = new javax.swing.JButton();
        jButtonVenderProdutos = new javax.swing.JButton();
        jButtonVenderServicos = new javax.swing.JButton();
        jButtonListarFuncionarios = new javax.swing.JButton();
        jButtonListarClientes = new javax.swing.JButton();
        jButtonListarOrdensServico = new javax.swing.JButton();
        jButtonRegistrarTratamento = new javax.swing.JButton();
        jButtonReporEstoque = new javax.swing.JButton();
        jButtonPagarContas = new javax.swing.JButton();
        jButtonGerarRelatorios = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Menu Administrador");

        jButtonCadastrarNovoCliente.setText("CADASTRAR NOVO CLIENTE");
        jButtonCadastrarNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarNovoClienteActionPerformed(evt);
            }
        });

        jButtonCadastrarNovoVendedor.setText("CADASTRAR NOVO VENDEDOR");
        jButtonCadastrarNovoVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarNovoVendedorActionPerformed(evt);
            }
        });

        jButtonCadastrarNovoVeterinario.setText("CADASTRAR NOVO VETERINÁRIO");
        jButtonCadastrarNovoVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarNovoVeterinarioActionPerformed(evt);
            }
        });

        jButtonCadastrarNovoProduto.setText("CADASTRAR NOVO PRODUTO");
        jButtonCadastrarNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarNovoProdutoActionPerformed(evt);
            }
        });

        jButtonCadastrarNovoServico.setText("CADASTRAR NOVO SERVIÇO");
        jButtonCadastrarNovoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarNovoServicoActionPerformed(evt);
            }
        });

        jButtonVenderProdutos.setText("VENDER PRODUTOS");
        jButtonVenderProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVenderProdutosActionPerformed(evt);
            }
        });

        jButtonVenderServicos.setText("VENDER SERVIÇOS");
        jButtonVenderServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVenderServicosActionPerformed(evt);
            }
        });

        jButtonListarFuncionarios.setText("LISTAR FUNCIONÁRIOS");
        jButtonListarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarFuncionariosActionPerformed(evt);
            }
        });

        jButtonListarClientes.setText("LISTAR CLIENTES");
        jButtonListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarClientesActionPerformed(evt);
            }
        });

        jButtonListarOrdensServico.setText("LISTAR ORDENS DE SERVIÇOS");
        jButtonListarOrdensServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarOrdensServicoActionPerformed(evt);
            }
        });

        jButtonRegistrarTratamento.setText("REGISTRAR TRATAMENTO");
        jButtonRegistrarTratamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarTratamentoActionPerformed(evt);
            }
        });

        jButtonReporEstoque.setText("REPOR ESTOQUE");
        jButtonReporEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReporEstoqueActionPerformed(evt);
            }
        });

        jButtonPagarContas.setText("PAGAR CONTAS");
        jButtonPagarContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPagarContasActionPerformed(evt);
            }
        });

        jButtonGerarRelatorios.setText("GERAR RELATÓRIOS");
        jButtonGerarRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarRelatoriosActionPerformed(evt);
            }
        });

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonPagarContas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonRegistrarTratamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonListarClientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonVenderServicos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCadastrarNovoServico, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCadastrarNovoVeterinario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(jButtonCadastrarNovoCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonReporEstoque, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonListarOrdensServico, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(jButtonListarFuncionarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonVenderProdutos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCadastrarNovoVendedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCadastrarNovoProduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonGerarRelatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrarNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCadastrarNovoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrarNovoVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCadastrarNovoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrarNovoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVenderProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVenderServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonListarFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonListarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonListarOrdensServico, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegistrarTratamento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonReporEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPagarContas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGerarRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonVoltar)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        String message = "Deseja realmente sair do Menu de Administrador?";
        String title = "Confirmação";
        int resposta = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION){
            petshop.voltar();
        }
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonGerarRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarRelatoriosActionPerformed
        petshop.irPara(new TelaRelatorio(petshop));         
    }//GEN-LAST:event_jButtonGerarRelatoriosActionPerformed

    private void jButtonPagarContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagarContasActionPerformed
        petshop.irPara(new TelaPagarContas(petshop));   
    }//GEN-LAST:event_jButtonPagarContasActionPerformed

    private void jButtonReporEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReporEstoqueActionPerformed
        petshop.irPara(new TelaReporEstoque(petshop)); 
    }//GEN-LAST:event_jButtonReporEstoqueActionPerformed

    private void jButtonRegistrarTratamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarTratamentoActionPerformed
        petshop.irPara(new TelaRegistrarTratamento(petshop)); 
    }//GEN-LAST:event_jButtonRegistrarTratamentoActionPerformed

    private void jButtonListarOrdensServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarOrdensServicoActionPerformed
        petshop.irPara(new TelaDeServicos(petshop)); 
    }//GEN-LAST:event_jButtonListarOrdensServicoActionPerformed

    private void jButtonListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarClientesActionPerformed
        petshop.irPara(new TelaDeClientes(petshop)); 
    }//GEN-LAST:event_jButtonListarClientesActionPerformed

    private void jButtonListarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarFuncionariosActionPerformed
        petshop.irPara(new TelaDeFuncionarios(petshop)); 
    }//GEN-LAST:event_jButtonListarFuncionariosActionPerformed

    private void jButtonVenderServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVenderServicosActionPerformed
        petshop.irPara(new TelaVenderServicos(petshop)); 
    }//GEN-LAST:event_jButtonVenderServicosActionPerformed

    private void jButtonVenderProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVenderProdutosActionPerformed
        petshop.irPara(new TelaVenderProdutos(petshop)); 
    }//GEN-LAST:event_jButtonVenderProdutosActionPerformed

    private void jButtonCadastrarNovoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarNovoServicoActionPerformed
        petshop.irPara(new TelaCadastroServico(petshop)); 
    }//GEN-LAST:event_jButtonCadastrarNovoServicoActionPerformed

    private void jButtonCadastrarNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarNovoProdutoActionPerformed
        petshop.irPara(new TelaCadastroProduto(petshop)); 
    }//GEN-LAST:event_jButtonCadastrarNovoProdutoActionPerformed

    private void jButtonCadastrarNovoVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarNovoVeterinarioActionPerformed
        petshop.irPara(new TelaCadastroFuncionario(petshop)); 
    }//GEN-LAST:event_jButtonCadastrarNovoVeterinarioActionPerformed

    private void jButtonCadastrarNovoVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarNovoVendedorActionPerformed
        petshop.irPara(new TelaCadastroFuncionario(petshop)); 
    }//GEN-LAST:event_jButtonCadastrarNovoVendedorActionPerformed

    private void jButtonCadastrarNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarNovoClienteActionPerformed
        petshop.irPara(new TelaCadastroCliente(petshop)); 
    }//GEN-LAST:event_jButtonCadastrarNovoClienteActionPerformed
           

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarNovoCliente;
    private javax.swing.JButton jButtonCadastrarNovoProduto;
    private javax.swing.JButton jButtonCadastrarNovoServico;
    private javax.swing.JButton jButtonCadastrarNovoVendedor;
    private javax.swing.JButton jButtonCadastrarNovoVeterinario;
    private javax.swing.JButton jButtonGerarRelatorios;
    private javax.swing.JButton jButtonListarClientes;
    private javax.swing.JButton jButtonListarFuncionarios;
    private javax.swing.JButton jButtonListarOrdensServico;
    private javax.swing.JButton jButtonPagarContas;
    private javax.swing.JButton jButtonRegistrarTratamento;
    private javax.swing.JButton jButtonReporEstoque;
    private javax.swing.JButton jButtonVenderProdutos;
    private javax.swing.JButton jButtonVenderServicos;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
